/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien_01;

/**
 *
 * @author Gogojungle
 */

import component.LopHoc;
import component.Lop_MonHoc;
import component.MonHoc;
import component.School;
import component.SinhVien;
import component.ThoiKhoaBieu;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static quanlysinhvien_01.managementClassRoom.sc;

public class managementSchedule extends javax.swing.JFrame {

    private String className = "";
    private String idSubject = "";
    private final int IMPORT_FILE = 1;
    private final int EXPORT_FILE = 2;
    
    private String[] columnNames = {
        "STT", "Mã môn", "Tên môn", "Phòng học"
    };
    
    private final String[] columnNamesStudent = {
        "STT", "MSSV", "Họ tên", "Giới tính", "CMND"
    };
    
    addSV addSV;
    managementClassRoom manageCR;
    /**
     * Creates new form managementSchedule
     */
    public managementSchedule() {
//        this.manageCR.setVisible(false);
        initComponents();
        initLayout();        
//        manageCR = new managementClassRoom();
        manageCR.setVisible(false);
        
    }
    
    public managementSchedule(String className){
        this.className = className;
        initComponents();
        initLayout();
        this.manageCR.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTKB = new javax.swing.JTable();
        btnImportTKB = new javax.swing.JButton();
        cbBoxMHId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lableNotify = new javax.swing.JLabel();
        panelListSV = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDSSVSubject = new javax.swing.JTable();
        lableDSSVLop = new javax.swing.JLabel();
        lableTKB = new javax.swing.JLabel();
        btnAddSVBySubject = new javax.swing.JButton();
        btnReLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thời Khóa Biểu");
        setFocusCycleRoot(false);

        tableTKB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableTKB);

        btnImportTKB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImportTKB.setText("Import");
        btnImportTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportTKBActionPerformed(evt);
            }
        });

        cbBoxMHId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoxMHIdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Môn Học:");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lableNotify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lableNotify.setForeground(new java.awt.Color(255, 0, 0));
        lableNotify.setText("jLabel3");

        tableDSSVSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDSSVSubject);

        lableDSSVLop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lableDSSVLop.setText("DSSV");

        javax.swing.GroupLayout panelListSVLayout = new javax.swing.GroupLayout(panelListSV);
        panelListSV.setLayout(panelListSVLayout);
        panelListSVLayout.setHorizontalGroup(
            panelListSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListSVLayout.createSequentialGroup()
                .addGroup(panelListSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListSVLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lableDSSVLop))
                    .addGroup(panelListSVLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListSVLayout.setVerticalGroup(
            panelListSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListSVLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lableDSSVLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        lableTKB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lableTKB.setText("TKB");

        btnAddSVBySubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddSVBySubject.setText("Thêm SV");
        btnAddSVBySubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSVBySubjectActionPerformed(evt);
            }
        });

        btnReLoad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReLoad.setText("Reload");
        btnReLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lableTKB)
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lableNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbBoxMHId, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImportTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnAddSVBySubject)
                        .addGap(33, 33, 33)
                        .addComponent(btnReLoad)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lableTKB)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(cbBoxMHId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImportTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddSVBySubject, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lableNotify)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panelListSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportTKBActionPerformed
        // TODO add your handling code here:
        importExportFile("Choose file import", IMPORT_FILE);
    }//GEN-LAST:event_btnImportTKBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.manageCR.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbBoxMHIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoxMHIdActionPerformed
        // TODO add your handling code here:        
        addDataTableSchedule();
    }//GEN-LAST:event_cbBoxMHIdActionPerformed

    private void btnAddSVBySubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSVBySubjectActionPerformed
        // TODO add your handling code here:
        String idMH = String.valueOf(cbBoxMHId.getItemAt(cbBoxMHId.getSelectedIndex()));
        if (cbBoxMHId.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "!!! Vui Lòng Chọn Môn Học");
        } else {
            addSV = new addSV(className, idMH);
            addSV.setVisible(true);
        }        
    }//GEN-LAST:event_btnAddSVBySubjectActionPerformed

    private void btnReLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReLoadActionPerformed
        // TODO add your handling code here:
        addDataTableSchedule();        
    }//GEN-LAST:event_btnReLoadActionPerformed
    
    private void initLayout(){
        panelListSV.setVisible(false);
        addDataForComboBoxClass();        
    }
    
    private void addDataForComboBoxClass(){
        manageCR = new managementClassRoom();
        System.out.println("Class Name:  " + className);
        lableTKB.setText("Thời Khóa Biểu " + className); 
        ArrayList<LopHoc> listLH = sc.getList();
        DefaultComboBoxModel cbBox = new DefaultComboBoxModel();
        DefaultTableModel tblTKB = new DefaultTableModel();
        
        for (LopHoc i : listLH) {                   
            ArrayList<ThoiKhoaBieu> listSchedule = i.getTKB();
            if(listSchedule.size() > 0){
                lableNotify.setVisible(false);                               
                tblTKB.setColumnIdentifiers(columnNames);
                int stt = 1;
                for(ThoiKhoaBieu item : listSchedule){
                    
                    String[] info = new String[4];
                    info[0] = String.valueOf(stt);
                    info[1] = item.getMH().getMaMH();
                    info[2] = item.getMH().getTenMH();
                    info[3] = item.getPH();
                    
                    System.out.println("Mã MH: " + item.getMH().getMaMH());

                    cbBox.addElement(item.getMH().getMaMH()); // add từng mã môn vào comboBox
                    tblTKB.addRow(info);
                    stt++;
                }                
                tableTKB.setModel(tblTKB);
                cbBoxMHId.setModel(cbBox);
            } else {
                lableNotify.setText("Chưa Có Thời Khóa Biểu!!!!");
                tblTKB.setColumnIdentifiers(columnNames);
                tableTKB.setModel(tblTKB);
            }           
        }          
    }
       
    
    private void addDataTableSchedule(){
        lableDSSVLop.setVisible(false);
        DefaultTableModel tableDSSV = new DefaultTableModel();
        
        String valueComboBox = cbBoxMHId.getSelectedItem().toString();        
        Lop_MonHoc lop_MH = sc.getLopMonHoc(className, valueComboBox);
        
//        System.out.println("Lớp - Môn Học:  " + className + " - " + valueComboBox);
        
        if(!(valueComboBox.isEmpty())){
            lableDSSVLop.setVisible(true);
            lableDSSVLop.setText("Danh Sách Sinh Viên: " + className + " - " + valueComboBox);
            panelListSV.setVisible(true);
            
            tableDSSV.setColumnIdentifiers(columnNamesStudent);
            
            ArrayList<SinhVien> listSV = lop_MH.getListSV();
            int stt = 1;
            for(SinhVien sv : listSV){                
                String[] rows = new String[5];
                rows[0] = String.valueOf(stt);
                rows[1] = sv.getMSSV();
                rows[2] = sv.getName();
                    if (sv.getSex() == 0) {
                        rows[3] = "Nữ";
                    } else {
                        rows[3] = "Nam";
                    }
                rows[4] = sv.getCMND();
                
                tableDSSV.addRow(rows);
                stt++;
            }
            tableDSSVSubject.setModel(tableDSSV);
        } else {
            tableDSSV.setColumnIdentifiers(columnNamesStudent);
            tableDSSVSubject.setModel(tableDSSV);
        }
    }
    
    private void importExportFile(String title, int type) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle(title);
        int choose = -1;
        switch (type) {
            case IMPORT_FILE:
                choose = fileChooser.showOpenDialog(null);
                break;
            case EXPORT_FILE:
                choose = fileChooser.showSaveDialog(null);
                break;
        }

        if (choose == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            switch (type) {
                case IMPORT_FILE:
                    readFile(f);
                    break;
                case EXPORT_FILE:
                    writeFile(f);
                    break;
            }
        }
    }
    
    private void readFile(File file) {
        try {
            try (FileReader reader = new FileReader(file)) {
                BufferedReader buffer = new BufferedReader(reader);

                String line;
                line = buffer.readLine();
//                System.out.println("File import: " + line);
                String[] tenLop = line.split(",");
                LopHoc lh = new LopHoc();
                ArrayList<Lop_MonHoc> class_subject = new ArrayList<Lop_MonHoc>();
                
                lh = sc.getLopHoc(tenLop[0]);
//                System.out.println("tenLop[0]: " + tenLop[0]);
                if(tenLop[0].equals(className)) {                                
                    // get tkb
                    while ((line = buffer.readLine()) != null) {
                        String[] info = line.split(",");
                        
                        MonHoc monHoc = new MonHoc(info[0], info[1]);
                        ThoiKhoaBieu tKB = new ThoiKhoaBieu(monHoc, info[2]);
                        
                        // Add TKB vào lớp học
                        lh.addThoiKhoaBieu(tKB);
                        
                        Lop_MonHoc classSubject = new Lop_MonHoc();
                        classSubject.setClassName(className);
                        classSubject.setMaMonHoc(info[0]);
                        classSubject.setListSV(lh.getListSinhVien());
                        
                        class_subject.add(classSubject);
                    }
                    sc.setListLopMonHoc(class_subject);
                    sc.setLopHoc(lh, className);
                
                buffer.close();
                } else {
                    JOptionPane.showMessageDialog(null, "!!! Thời Khóa Biểu Sai Lớp");
                }
                
                System.out.println(sc.getListMHClass().size());
            }
            initLayout();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error to open file: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void writeFile(File file) {
        try{              
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error to export file: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managementSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managementSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managementSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managementSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managementSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSVBySubject;
    private javax.swing.JButton btnImportTKB;
    private javax.swing.JButton btnReLoad;
    private javax.swing.JComboBox<String> cbBoxMHId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lableDSSVLop;
    private javax.swing.JLabel lableNotify;
    private javax.swing.JLabel lableTKB;
    private javax.swing.JPanel panelListSV;
    private javax.swing.JTable tableDSSVSubject;
    private javax.swing.JTable tableTKB;
    // End of variables declaration//GEN-END:variables
}
